apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pod.yml

images:
- name: x-image
  newName: wericknalyson/gitopslanlink
  newTag: 26af07c5e50f00d59d7179f7db0fbfc898d07f26
